services:
  - type: web
    name: virtualstagingai
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
    healthCheckPath: /up
    disk:
      name: rails-storage
      mountPath: /rails/storage
      sizeGB: 1
